const CACHE='itgold-v4';
const ASSETS=['/','/share.html','/manifest.webmanifest','/itgold-icon.svg'];
const SHARE_MARKUP='<div id="itgoldShareQuick" style="max-width:1050px;margin:0 auto;padding:0 20px 16px"><a href="/share.html" style="display:block;width:100%;padding:14px;border-radius:12px;background:#151515;color:#f4c44e;border:1px solid #6e5517;font-family:Arial,sans-serif;font-weight:900;text-align:center;text-decoration:none;box-sizing:border-box">▣ SHARE IT GOLD — SHOW QR CODE</a></div>';
function addShareButton(html){if(html.includes('id="itgoldShareQuick"'))return html;return html.replace('<div class="wrap">',SHARE_MARKUP+'<div class="wrap">')}
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)))});
self.addEventListener('activate',e=>e.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k))))])));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin===self.location.origin&&(u.pathname==='/'||u.pathname==='/index.html')){e.respondWith(fetch(e.request).then(async r=>{if(!r.ok)return r;const type=r.headers.get('content-type')||'';if(!type.includes('text/html'))return r;const html=addShareButton(await r.text());return new Response(html,{status:r.status,statusText:r.statusText,headers:r.headers})}).catch(async()=>{const r=await caches.match('/');if(!r)return Response.error();const html=addShareButton(await r.text());return new Response(html,{status:200,headers:{'content-type':'text/html; charset=utf-8'}})}));return}e.respondWith(fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r}).catch(()=>caches.match(e.request)))});
self.addEventListener('message',e=>{if(e.data?.type==='SHOW_NOTIFICATION'){const title=e.data.title||'IT Gold';const options={body:e.data.body||'',icon:'/itgold-icon.svg',badge:'/itgold-icon.svg',data:{url:e.data.url||'/'}};e.waitUntil(self.registration.showNotification(title,options))}});
self.addEventListener('push',e=>{let d={};try{d=e.data?e.data.json():{}}catch{d={body:e.data?e.data.text():''}}const title=d.title||'IT Gold';const options={body:d.body||'New IT Gold activity needs your attention.',icon:'/itgold-icon.svg',badge:'/itgold-icon.svg',tag:d.tag||'itgold-owner-alert',renotify:true,vibrate:[200,100,200],data:{url:d.url||'/admin.html'}};e.waitUntil(self.registration.showNotification(title,options))});
self.addEventListener('notificationclick',e=>{e.notification.close();const url=e.notification.data?.url||'/admin.html';e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const c of list){if('focus' in c){c.navigate(url);return c.focus()}}return clients.openWindow(url)}))});